apiVersion: v1
kind: Service
metadata:
  name: java-web-app-service
  namespace: test-space
spec:
  selector:
    app: java-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
