name: 'Terraform Setup'
description: 'Installing and init Terraform'

inputs:
  AWS_REGION:
    description: 'AWS region'
    required: true
  AWS_BUCKET_NAME:
    description: 'S3 bucket name for terraform stae file'
    required: true
  AWS_BUCKET_KEY_NAME:
    description: 'S3 bucket key for terraform stae file'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform initialization
      id: init
      shell: bash
      working-directory: ./terraform-code
      run: terraform init -backend-config="bucket=${{ inputs.AWS_BUCKET_NAME }}" -backend-config="key=${{ inputs.AWS_BUCKET_KEY_NAME }}" -backend-config="region=${{ inputs.AWS_REGION }}" -input=false