apiVersion: v1
kind: Service
metadata:
  name: java-web-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: java-web-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
