---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: java-web-app-pdb
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{ include "webAppLabel" . | indent 4 }}