name: 'Destroy'
on:
  workflow_call:
    inputs:
      CLUSTER_NAME:
        required: true
        type: string
      HELM_REVISION_NAME:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      AWS_BUCKET_NAME:
        required: true
        type: string
      AWS_BUCKET_KEY_NAME:
        required: true
        type: string

permissions:
  id-token: write 
  contents: read 

env:
  TF_LOG: INFO

jobs:
  call-test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
      AWS_BUCKET_KEY_NAME: ${{ vars.AWS_BUCKET_KEY_NAME }}
    secrets: inherit

  helm-uninstall:
    name: Uninstall Helm
    needs: call-test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Run aws auth
        uses: ./.github/composite-actions/aws-auth
        with:
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_REGION: ${{ inputs.AWS_REGION }}

      - name: Helm and kubectl setup
        uses: ./.github/composite-actions/helm-setup
        with:
          CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
          AWS_REGION: ${{ inputs.AWS_REGION }}

      - name: Uninstalling Application using Helm
        run: |
          helm uninstall ${{ inputs.HELM_REVISION_NAME }}

  terraform-destroy:
    name: Destroying Terraform
    runs-on: ubuntu-latest
    needs: helm-uninstall
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run aws auth
        uses: ./.github/composite-actions/aws-auth
        with:
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_REGION: ${{ inputs.AWS_REGION }}

      - name: Terraform setup
        uses: ./.github/composite-actions/terraform-setup
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ inputs.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ inputs.AWS_BUCKET_KEY_NAME }}

      - name: Get tfvars file from secret
        env: 
          vars_file: ${{ secrets.TF_VARS }}
        if: ${{ env.vars_file != '' }}
        working-directory: ./terraform-code
        run: echo "${{ secrets.TF_VARS }}" > terraform.tfvars

      - name: Terraform Destroy
        working-directory: ./terraform-code
        run: terraform destroy -auto-approve -input=false