name: "Main"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: apply or destroy'
        required: true
        default: 'apply'
permissions:
  id-token: write 
  contents: read 

jobs:
  call-test:
    name: Test
    if: github.event.inputs.action != 'destroy'
    uses: ./.github/workflows/test.yml
    with:
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
      AWS_BUCKET_KEY_NAME: ${{ vars.AWS_BUCKET_KEY_NAME }}
    secrets: inherit
  
  call-deploy:
    name: Deploy
    needs: call-test
    if: github.event.inputs.action != 'destroy'
    uses: ./.github/workflows/deploy.yml
    with:
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
      AWS_BUCKET_KEY_NAME: ${{ vars.AWS_BUCKET_KEY_NAME }}
    secrets: inherit
  
  call-destroy:
    name: Destroy
    if: github.event.inputs.action == 'destroy'
    uses: ./.github/workflows/destroy.yml
    with:
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
      AWS_BUCKET_KEY_NAME: ${{ vars.AWS_BUCKET_KEY_NAME }}
    secrets: inherit