name: "Build and Push"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: apply or destroy'
        required: true
        default: 'apply'
permissions:
  id-token: write 
  contents: read 

jobs:

  call-build-app:
    name: Build
    if: github.event.inputs.action != 'destroy'
    uses: ./.github/workflows/build-app.yml

  call-docker-build-and-push:
    name: Docker
    if: github.event.inputs.action != 'destroy'
    needs: call-build-app
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      ECR_REPO: ${{ vars.ECR_REPO }}
    secrets: inherit

  call-test:
    name: Test
    if: github.event.inputs.action != 'destroy'
    needs: call-docker-build-and-push
    uses: ./.github/workflows/test.yml
    with:
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
    secrets: inherit
  
  call-deploy:
    name: Deploy
    needs: call-test
    if: github.event.inputs.action != 'destroy'
    uses: ./.github/workflows/deploy.yml
    with:
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      HELM_REVISION_NAME: ${{ vars.HELM_REVISION_NAME }}
      ECR_REPO: ${{ vars.ECR_REPO }}
    secrets: inherit
  
  call-destroy:
    name: Destroy
    if: github.event.inputs.action == 'destroy'
    uses: ./.github/workflows/destroy.yml
    with:
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      HELM_REVISION_NAME: ${{ vars.HELM_REVISION_NAME }}
    secrets: inherit