name: 'Test'
on:
  workflow_call:
    inputs:
      CLUSTER_NAME:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      AWS_BUCKET_NAME:
        required: true
        type: string
      AWS_BUCKET_KEY_NAME:
        required: true
        type: string

permissions:
  id-token: write 
  contents: read 
      
env:
  TF_LOG: INFO

jobs:
  terraform-test:
    name: Tetsing Terraform code
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run aws auth
        uses: ./.github/composite-actions/aws-auth
        with:
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_REGION: ${{ inputs.AWS_REGION }}

      - name: Terraform setup
        uses: ./.github/composite-actions/terraform-setup
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ inputs.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ inputs.AWS_BUCKET_KEY_NAME }}

      - name: Decode and create .tfvars file
        if: secrets.TF_VARS != ''
        working-directory: ./terraform-code
        run: echo "${{ secrets.TF_VARS }}" > terraform.tfvars && cat terraform.tfvars


      - name: Test Terraform Syntax
        working-directory: ./terraform-code
        run: terraform fmt && terraform validate -no-color

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ./terraform-code
        run: terraform plan -no-color